{
 "title": "IUT",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pression E007",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "sae23",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(CONCAT(`date`, ' ', `heure`)) * 1000 AS `time`,\r\n  `valeur` AS pressure\r\nFROM `Mesure`\r\nWHERE `id_capteur` = 'Press_E007'\r\n  AND `date` >= CURDATE() - INTERVAL 1 DAY\r\nORDER BY `date` ASC, `heure` ASC;"
    }
   ]
  },
  {
   "title": "Température E007",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "sae23",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(CONCAT(`date`, ' ', `heure`)) * 1000 AS `time`,\r\n  `valeur` AS temperature\r\nFROM `Mesure`\r\nWHERE `id_capteur` = 'Temp_E007'\r\n  AND `date` >= CURDATE() - INTERVAL 1 DAY\r\nORDER BY `date` ASC, `heure` ASC;\r\n"
    }
   ]
  },
  {
   "title": "Luminosité E100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "sae23",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(CONCAT(`date`, ' ', `heure`)) * 1000 AS `time`,\r\n  `valeur` AS illumination\r\nFROM `Mesure`\r\nWHERE `id_capteur` = 'Illum_E100'\r\n  AND `date` >= CURDATE() - INTERVAL 1 DAY\r\nORDER BY `date` ASC, `heure` ASC;"
    }
   ]
  },
  {
   "title": "Température E100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "sae23",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(CONCAT(`date`, ' ', `heure`)) * 1000 AS `time`,\r\n  `valeur` AS temperature\r\nFROM `Mesure`\r\nWHERE `id_capteur` = 'Temp_E100'\r\n  AND `date` >= CURDATE() - INTERVAL 1 DAY\r\nORDER BY `date` ASC, `heure` ASC;"
    }
   ]
  },
  {
   "title": "CO2 E003",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "sae23",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(CONCAT(`date`, ' ', `heure`)) * 1000 AS `time`,\r\n  `valeur` AS co2\r\nFROM `Mesure`\r\nWHERE `id_capteur` = 'CO2_E003'\r\n  AND `date` >= CURDATE() - INTERVAL 1 DAY\r\nORDER BY `date` ASC, `heure` ASC;"
    }
   ]
  },
  {
   "title": "Humidité E003",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "sae23",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(CONCAT(`date`, ' ', `heure`)) * 1000 AS `time`,\r\n  `valeur` AS humidity\r\nFROM `Mesure`\r\nWHERE `id_capteur` = 'Hum_E003'\r\n  AND `date` >= CURDATE() - INTERVAL 1 DAY\r\nORDER BY `date` ASC, `heure` ASC;"
    }
   ]
  },
  {
   "title": "Température E003",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "sae23",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(CONCAT(`date`, ' ', `heure`)) * 1000 AS `time`,\r\n  `valeur` AS temperature\r\nFROM `Mesure`\r\nWHERE `id_capteur` = 'Temp_E003'\r\n  AND `date` >= CURDATE() - INTERVAL 1 DAY\r\nORDER BY `date` ASC, `heure` ASC;"
    }
   ]
  }
 ]
}